package:
  name: skll
  version: 2.5

source:
  path: ../../../skll

build:
  number: 0
  script:
    - cd $SRC_DIR
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - compute_eval_from_predictions = skll.utils.commandline.compute_eval_from_predictions:main
    - filter_features = skll.utils.commandline.filter_features:main
    - generate_predictions = skll.utils.commandline.generate_predictions:main
    - join_features = skll.utils.commandline.join_features:main
    - plot_learning_curves = skll.utils.commandline.plot_learning_curves:main
    - print_model_weights = skll.utils.commandline.print_model_weights:main
    - run_experiment = skll.utils.commandline.run_experiment:main
    - skll_convert = skll.utils.commandline.skll_convert:main
    - summarize_results = skll.utils.commandline.summarize_results:main
    - compute_eval_from_predictions = skll.utils.commandline.compute_eval_from_predictions:main
    - filter_features = skll.utils.commandline.filter_features:main
    - generate_predictions = skll.utils.commandline.generate_predictions:main
    - join_features = skll.utils.commandline.join_features:main
    - plot_learning_curves = skll.utils.commandline.plot_learning_curves:main
    - print_model_weights = skll.utils.commandline.print_model_weights:main
    - run_experiment = skll.utils.commandline.run_experiment:main
    - skll_convert = skll.utils.commandline.skll_convert:main
    - summarize_results = skll.utils.commandline.summarize_results:main

requirements:
  build:
    - python
    - pip
    - setuptools
    - beautifulsoup4
    - joblib
    - mord
    - numpy {{ numpy }}
    - pandas
    - ruamel.yaml
    - scikit-learn >=0.24.1,<=0.24.2
    - scipy
    - seaborn
    - tabulate

  run:
    - python
    - beautifulsoup4
    - joblib
    - mord
    - numpy
    - pandas
    - ruamel.yaml
    - scikit-learn >=0.24.1,<=0.24.2
    - scipy
    - seaborn
    - tabulate

test:
  # Python imports
  imports:
    - skll

  commands:
    - compute_eval_from_predictions --help
    - filter_features --help
    - generate_predictions --help
    - join_features --help
    - plot_learning_curves --help
    - print_model_weights --help
    - run_experiment --help
    - skll_convert --help
    - summarize_results --help

about:
  home: http://github.com/EducationalTestingService/skll
  license: BSD
  license_file: LICENSE.txt
  summary: SciKit-Learn Laboratory makes it easier to run machine learning experiments with scikit-learn.
