# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more git_hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: .(tsv|csv|json|json)$
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: debug-statements
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
    -   id: isort
        args: ["--multi-line", "3", "--trailing-comma", "--use-parentheses", "--ensure-newline-before-comments", "--line-length", "88"]
-   repo: https://github.com/ikamensh/flynt/
    rev: '0.77'
    hooks:
    -   id: flynt
